go.property("enabled", true)
go.property("prefix", 1)

local custom_render = require("custom_render.custom_render")

local PREFIXES = {
    "main",
    "bootstrap"
}

local FRAME_CHAR = {
    ">", " "
}

function init(self)
end

function final(self)
end

function update(self, dt)
    if not self.enabled then
        return
    end

    print(string.format("%sFrame %05d, %10s, %13s, %.05f", FRAME_CHAR[custom_render.frame_num % 2 + 1], custom_render.frame_num, PREFIXES[self.prefix], "update", dt))
end

function fixed_update(self, dt)
    if not self.enabled then
        return
    end

    print(string.format("%sFrame %05d, %10s, %13s, %.05f", FRAME_CHAR[custom_render.frame_num % 2 + 1], custom_render.frame_num, PREFIXES[self.prefix], "fixed_update", dt))
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
