function init(self)
	self.mass = go.get("#collisionobject", "mass")
	self.gravity = physics.get_gravity()
end

function final(self)
end

function update(self, dt)
	msg.post("#collisionobject", "apply_force", {
		force = vmath.vector3(0, - self.mass * self.gravity.y, 0),
		position = go.get_world_position()
	})
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
